### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Populate the database with some data
GET {{url}}/hotels/populate/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}


> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}