### --- AUTH ENDPOINTS ---

### Test endpoint (no login required)
GET {{url}}/auth/test


### Create a new user - will get USER role by default
POST {{url}}/auth/register
Content-Type: application/json

{
  "username": "esben",
  "password": "1234"
}

###
POST {{url}}/auth/login/

{
    "username": "mia",
    "password": "1234"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}




### --- PERSON ENDPOINTS ---

### Get all persons
GET {{url}}/people
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Get person by id
GET {{url}}/people/1

### Get person by name
GET {{url}}/people/search?name=Mia

### Create (add) person
POST {{url}}/people
Content-Type: application/json

{
  "name": "Mia"
}

### Update person
PUT {{url}}/people/1
Content-Type: application/json

{
  "name": "Updated Mia"
}

### Delete person
DELETE {{url}}/people/1
